package com.devndev.lamp.presentation.ui.common

object Route {
    const val MAIN = "main"
    const val SPLASH = "splash"
    const val HOME = "home"
    const val CHAT_LIST = "chat_list"
    const val CHAT_LIST_WITH_ID = "chatList?chatRoomId={chatRoomId}"
    const val LOGIN = "login"
    const val EMAIL_LOGIN = "email_login"
    const val MYPAGE = "mypage"
    const val SEARCH = "search"
    const val CREATION = "creation/{isEdit}"
    const val REGISTRATION = "registration"
    const val INVITE = "invite"
    const val ALARM = "ALARM"
    const val SIGNUP = "signup"
    const val START_LAMP = "start_lamp"
    const val REVIEW = "review/{lampMatchId}"
    const val PROFILE_EDIT = "profile_edit"
    const val FORGOT_PASSWORD = "forgot_password"
    const val VOTE = "vote"
    const val FIND = "find"
    const val CHAT = "chat"
    const val APPOINTMENT = "appointment"
    const val REGISTER_APPOINTMENT = "register_appointment/{isEdit}/{chatAppointmentId}"
    const val ASSESSMENT_LIST = "assessment_list"
}
